apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: {{ include "shuttle-backend.fullname" . }}-weighted
  labels:
    {{- include "shuttle-backend.labels" . | nindent 4 }}
spec:
  weighted:
    services:
      - name: {{ include "shuttle-backend.fullname" . }}-blue
        port: {{ .Values.service.port }}
        weight: {{ .Values.traffic.blue }}
      - name: {{ include "shuttle-backend.fullname" . }}-green
        port: {{ .Values.service.port }}
        weight: {{ .Values.traffic.green }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "shuttle-backend.fullname" . }}-web
  labels:
    {{- include "shuttle-backend.labels" . | nindent 4 }}
spec:
  entryPoints:
    - {{ .Values.ingress.entryPoints.web }}
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - kind: TraefikService
          name: {{ include "shuttle-backend.fullname" . }}-weighted
