#!/usr/bin/env python3
"""shuttle-go 개발 환경 통합 실행 스크립트

기본 실행은 postgres를 보장한 뒤 backend-blue/backend-green을 재빌드/재시작하고 프론트엔드를 함께 시작한다.
traefik은 기본 실행에서 재시작하지 않고, 내려가 있을 때만 시작한다.
--all 옵션을 주면 전체 구성요소(traefik/postgres/backend-blue/backend-green/prometheus/node-exporter/cadvisor/grafana/otp)를 함께 (재)시작한다.
--all-no-otp 옵션을 주면 otp를 제외한 구성요소(traefik/postgres/backend-blue/backend-green/prometheus/node-exporter/cadvisor/grafana)만 함께 (재)시작한다.
개별 컴포넌트 플래그(예: --grafana, --traefik, --otp)로 선택 재시작도 가능하다.

사용법:
    python run_dev.py              # 기본 시작 (backend-blue/green rebuild/restart + frontend)
    python run_dev.py --all        # 전체 시작 (backend-blue/green + monitoring + otp + frontend)
    python run_dev.py --all-no-otp # otp 제외 전체 시작 (backend-blue/green + monitoring + frontend)
    python run_dev.py --otp        # otp만 재시작 + frontend
    python run_dev.py --traefik --grafana  # 지정 컴포넌트만 재시작 + frontend
    python run_dev.py --frontend   # 프론트엔드 서버만 시작
    python run_dev.py --down       # 기본 구성요소 종료(backend-blue/green + frontend 포트 정리)
    python run_dev.py --down --all # 전체 종료
    python run_dev.py --down --all-no-otp # otp 제외 전체 종료
    python run_dev.py --down --otp # otp만 종료
"""

import argparse
import http.server
import json
import os
import signal
import socket
import subprocess
import sys
import threading
import time
import urllib.parse
import urllib.request

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
ENV_FILE = os.path.join(PROJECT_DIR, ".env")
DEV_CONFIG_JS = os.path.join(PROJECT_DIR, "dev.config.js")
DEFAULT_FRONTEND_PORT = 8080
DEFAULT_BACKEND_HTTP_PORT = 80
DEFAULT_BACKEND_HTTPS_PORT = 443
DEFAULT_PROMETHEUS_HOST_PORT = 9090
COMPOSE_TIMEOUT = 60  # 컨테이너 healthy 대기 최대 초
HEALTH_POLL_INTERVAL_SEC = 1.0
FRONTEND_PORT = DEFAULT_FRONTEND_PORT
BACKEND_HTTP_PORT = DEFAULT_BACKEND_HTTP_PORT
BACKEND_HTTPS_PORT = DEFAULT_BACKEND_HTTPS_PORT
PROMETHEUS_HOST_PORT = DEFAULT_PROMETHEUS_HOST_PORT
FRONTEND_API_BASE = ""
HEALTH_URL = ""
BACKEND_BLUE_SERVICE = "backend-blue"
BACKEND_GREEN_SERVICE = "backend-green"
BACKEND_SERVICES = (BACKEND_BLUE_SERVICE, BACKEND_GREEN_SERVICE)
CORE_SERVICES = BACKEND_SERVICES
GATEWAY_SERVICE = "traefik"
POSTGRES_SERVICE = "postgres"
SERVICE_ORDER = (
    "traefik",
    POSTGRES_SERVICE,
    BACKEND_BLUE_SERVICE,
    BACKEND_GREEN_SERVICE,
    "prometheus",
    "node-exporter",
    "cadvisor",
    "grafana",
    "otp",
)
ALL_EXCEPT_OTP_SERVICES = tuple(name for name in SERVICE_ORDER if name != "otp")


# ── 유틸 ──────────────────────────────────────────────────

def log(msg: str) -> None:
    print(f"\033[1;36m[shuttle-go]\033[0m {msg}", flush=True)


def err(msg: str) -> None:
    print(f"\033[1;31m[shuttle-go]\033[0m {msg}", flush=True)


def run(cmd: str, **kwargs) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, shell=True, cwd=PROJECT_DIR, **kwargs)


def is_port_in_use(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        return s.connect_ex(("127.0.0.1", port)) == 0


def load_env_file(path: str) -> dict[str, str]:
    values: dict[str, str] = {}
    if not os.path.exists(path):
        return values
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if stripped.startswith("export "):
                stripped = stripped[len("export ") :].strip()
            if "=" not in stripped:
                continue
            key, raw_value = stripped.split("=", 1)
            key = key.strip()
            value = raw_value.strip()
            if (
                len(value) >= 2
                and ((value[0] == value[-1] == '"') or (value[0] == value[-1] == "'"))
            ):
                value = value[1:-1]
            values[key] = value
    return values


def get_env_int(env_map: dict[str, str], key: str, default: int) -> int:
    raw = os.environ.get(key, env_map.get(key, str(default))).strip()
    try:
        value = int(raw)
    except ValueError:
        err(f"{key} 값이 정수가 아닙니다: {raw}")
        sys.exit(1)
    if value < 1 or value > 65535:
        err(f"{key} 값은 1~65535 범위여야 합니다: {value}")
        sys.exit(1)
    return value


def local_url(path: str, port: int, scheme: str = "http") -> str:
    default_port = 80 if scheme == "http" else 443
    if port == default_port:
        return f"{scheme}://localhost{path}"
    return f"{scheme}://localhost:{port}{path}"


def write_dev_config_js() -> None:
    config = {
        "API_HTTP_PORT": BACKEND_HTTP_PORT,
        "API_HTTPS_PORT": BACKEND_HTTPS_PORT,
    }
    if FRONTEND_API_BASE:
        config["API_BASE_OVERRIDE"] = FRONTEND_API_BASE
    content = (
        "// Auto-generated by run_dev.py\n"
        "window.__SHUTTLE_DEV_CONFIG = Object.assign({}, window.__SHUTTLE_DEV_CONFIG || {}, "
        f"{json.dumps(config, ensure_ascii=False, indent=2)}"
        ");\n"
    )
    with open(DEV_CONFIG_JS, "w", encoding="utf-8") as f:
        f.write(content)

def configure_runtime_ports(validate_conflict: bool = True) -> None:
    global FRONTEND_PORT, BACKEND_HTTP_PORT, BACKEND_HTTPS_PORT, PROMETHEUS_HOST_PORT, FRONTEND_API_BASE, HEALTH_URL
    env_map = load_env_file(ENV_FILE)
    FRONTEND_PORT = get_env_int(env_map, "FRONTEND_PORT", DEFAULT_FRONTEND_PORT)
    BACKEND_HTTP_PORT = get_env_int(env_map, "BACKEND_HTTP_PORT", DEFAULT_BACKEND_HTTP_PORT)
    BACKEND_HTTPS_PORT = get_env_int(env_map, "BACKEND_HTTPS_PORT", DEFAULT_BACKEND_HTTPS_PORT)
    PROMETHEUS_HOST_PORT = get_env_int(
        env_map, "PROMETHEUS_HOST_PORT", DEFAULT_PROMETHEUS_HOST_PORT
    )
    FRONTEND_API_BASE = os.environ.get("FRONTEND_API_BASE", env_map.get("FRONTEND_API_BASE", "")).strip()

    if validate_conflict and FRONTEND_PORT == BACKEND_HTTP_PORT:
        err(
            "FRONTEND_PORT와 BACKEND_HTTP_PORT가 동일합니다. "
            f"(현재 {FRONTEND_PORT}) .env에서 둘 중 하나를 변경하세요."
        )
        sys.exit(1)

    HEALTH_URL = local_url("/health", BACKEND_HTTP_PORT, scheme="http")


# ── Docker Compose ────────────────────────────────────────

def ordered_services(services: list[str] | tuple[str, ...]) -> list[str]:
    service_set = set(services)
    return [name for name in SERVICE_ORDER if name in service_set]


def selected_services_from_args(args: argparse.Namespace) -> list[str]:
    selected: list[str] = []
    if args.traefik:
        selected.append("traefik")
    if args.postgres:
        selected.append(POSTGRES_SERVICE)
    if args.backend:
        selected.extend(BACKEND_SERVICES)
    if args.prometheus:
        selected.append("prometheus")
    if args.node_exporter:
        selected.append("node-exporter")
    if args.grafana:
        selected.append("grafana")
    if args.otp:
        selected.append("otp")
    return ordered_services(selected)


def wait_backend_healthy(timeout_sec: int) -> bool:
    log(
        "백엔드 health endpoint 대기 … "
        f"(URL: {HEALTH_URL}, 최대 {timeout_sec}초, {int(HEALTH_POLL_INTERVAL_SEC)}초 간격 폴링)"
    )
    deadline = time.monotonic() + timeout_sec
    last_error = ""
    while True:
        poll_started = time.monotonic()
        try:
            with urllib.request.urlopen(HEALTH_URL, timeout=HEALTH_POLL_INTERVAL_SEC) as resp:
                if _is_healthy_response(resp):
                    log("백엔드 정상 (healthy)")
                    return True
                last_error = f"unexpected response status={resp.status}"
        except Exception as exc:
            last_error = str(exc)

        now = time.monotonic()
        if now >= deadline:
            err(
                f"{timeout_sec}초 내 /health 확인이 실패했습니다 "
                f"(URL: {HEALTH_URL}, 마지막 오류: {last_error or 'unknown'})"
            )
            return False
        sleep_for = min(
            HEALTH_POLL_INTERVAL_SEC,
            max(0.0, HEALTH_POLL_INTERVAL_SEC - (now - poll_started)),
            deadline - now,
        )
        if sleep_for > 0:
            time.sleep(sleep_for)


def get_service_container_id(service: str) -> str:
    result = run(
        f"docker compose ps -q {service}",
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        return ""
    return result.stdout.strip()


def get_service_health_status(service: str) -> str:
    container_id = get_service_container_id(service)
    if not container_id:
        return "missing"
    inspect = run(
        "docker inspect --format "
        "'{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "
        f"{container_id}",
        capture_output=True,
        text=True,
    )
    if inspect.returncode != 0:
        return "unknown"
    return (inspect.stdout or "").strip().lower() or "unknown"


def wait_service_healthy(service: str, timeout_sec: int) -> bool:
    log(f"{service} health 대기 … (최대 {timeout_sec}초)")
    deadline = time.monotonic() + timeout_sec
    last_status = "unknown"
    while True:
        status = get_service_health_status(service)
        last_status = status
        if status in {"healthy", "running"}:
            log(f"{service} 정상 상태 ({status})")
            return True

        now = time.monotonic()
        if now >= deadline:
            err(f"{service} health 확인 실패 (마지막 상태: {last_status})")
            return False
        time.sleep(HEALTH_POLL_INTERVAL_SEC)


def _is_healthy_response(resp: urllib.request.addinfourl) -> bool:
    if resp.status != 200:
        return False
    body = resp.read().decode("utf-8", errors="ignore").strip()
    if not body:
        return True
    try:
        payload = json.loads(body)
    except json.JSONDecodeError:
        return True
    status = payload.get("status")
    return isinstance(status, str) and status.lower() == "healthy"


def ensure_gateway_running() -> None:
    # 기본 실행에서는 traefik을 재시작/재빌드하지 않는다.
    # 다만 내려가 있으면 API 접근 경로 확보를 위해 시작만 수행한다.
    gateway_running = run(
        f"docker compose ps --status running -q {GATEWAY_SERVICE}",
        capture_output=True,
        text=True,
    )
    if not gateway_running.stdout.strip():
        log("traefik 미실행 상태 감지 → 시작만 수행 (재시작/재빌드 없음)")
        gateway_ret = run(f"docker compose up -d {GATEWAY_SERVICE}")
        if gateway_ret.returncode != 0:
            err("traefik 시작 실패")
            sys.exit(1)
    else:
        log("traefik 실행 중 → 재시작 없이 유지")


def ensure_postgres_running(timeout_sec: int = COMPOSE_TIMEOUT) -> None:
    if get_service_health_status(POSTGRES_SERVICE) not in {"healthy", "running"}:
        log("postgres 미실행 상태 감지 → 시작")
        ret = run(f"docker compose up -d {POSTGRES_SERVICE}")
        if ret.returncode != 0:
            err("postgres 시작 실패")
            sys.exit(1)
    if not wait_service_healthy(POSTGRES_SERVICE, timeout_sec):
        err("postgres health 확인 실패")
        sys.exit(1)


def compose_down(all_services: bool = False) -> None:
    if all_services:
        log("Docker Compose 전체 종료 중 …")
        run("docker compose down", stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        log("Docker Compose 전체 종료 완료")
        return

    services = " ".join(CORE_SERVICES)
    log(f"Docker Compose 기본 구성요소 종료 중 … ({services})")
    run(f"docker compose stop {services}", stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    run(f"docker compose rm -f {services}", stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    log("Docker Compose 기본 구성요소 종료 완료")


def compose_down_selected(services: list[str]) -> None:
    ordered = ordered_services(services)
    if not ordered:
        return
    service_expr = " ".join(ordered)
    log(f"선택 구성요소 종료 중 … ({service_expr})")
    run(f"docker compose stop {service_expr}", stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    run(f"docker compose rm -f {service_expr}", stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    log("선택 구성요소 종료 완료")


def compose_up_core() -> None:
    ensure_gateway_running()
    ensure_postgres_running(COMPOSE_TIMEOUT)

    services = " ".join(CORE_SERVICES)
    log(f"기본 구성요소 빌드 & 시작 … ({services})")
    ret = run(f"docker compose up -d --build --force-recreate --remove-orphans {services}")
    if ret.returncode != 0:
        err("기본 구성요소 docker compose up 실패")
        sys.exit(1)

    if not wait_backend_healthy(COMPOSE_TIMEOUT):
        err(f"{COMPOSE_TIMEOUT}초 내에 백엔드가 응답하지 않았습니다")
        sys.exit(1)


def compose_up_selected(services: list[str]) -> None:
    ordered = ordered_services(services)
    includes_backend = any(svc in BACKEND_SERVICES for svc in ordered)
    includes_postgres = POSTGRES_SERVICE in ordered

    if includes_backend and GATEWAY_SERVICE not in ordered:
        ensure_gateway_running()
    if includes_backend:
        ensure_postgres_running(COMPOSE_TIMEOUT)
        ordered = [svc for svc in ordered if svc != POSTGRES_SERVICE]
    elif includes_postgres:
        ensure_postgres_running(COMPOSE_TIMEOUT)
        ordered = [svc for svc in ordered if svc != POSTGRES_SERVICE]

    if not ordered:
        return

    service_expr = " ".join(ordered)

    log(f"선택 구성요소 시작 … ({service_expr})")
    if includes_backend:
        ret = run(f"docker compose up -d --build --force-recreate --remove-orphans {service_expr}")
    else:
        ret = run(f"docker compose up -d {service_expr}")
    if ret.returncode != 0:
        err("선택 구성요소 docker compose up 실패")
        sys.exit(1)

    if includes_backend and not wait_backend_healthy(COMPOSE_TIMEOUT):
        err(f"{COMPOSE_TIMEOUT}초 내에 백엔드가 응답하지 않았습니다")
        sys.exit(1)


def compose_up_all() -> None:
    compose_up_core()
    extra_services = ordered_services(
        [
            name
            for name in SERVICE_ORDER
            if name not in {GATEWAY_SERVICE, POSTGRES_SERVICE, *BACKEND_SERVICES}
        ]
    )
    if not extra_services:
        return
    service_expr = " ".join(extra_services)
    log(f"backend 외 구성요소 재시작 … ({service_expr})")
    ret = run(f"docker compose up -d --build --force-recreate --remove-orphans {service_expr}")
    if ret.returncode != 0:
        err("backend 외 구성요소 docker compose up 실패")
        sys.exit(1)


def compose_up_all_except_otp() -> None:
    compose_up_core()
    service_expr = " ".join(
        ordered_services(
            [
                name
                for name in ALL_EXCEPT_OTP_SERVICES
                if name not in {GATEWAY_SERVICE, POSTGRES_SERVICE, *BACKEND_SERVICES}
            ]
        )
    )
    if not service_expr:
        return
    log(f"OTP 제외 기타 구성요소 재시작 … ({service_expr})")
    ret = run(f"docker compose up -d --build --force-recreate --remove-orphans {service_expr}")
    if ret.returncode != 0:
        err("OTP 제외 전체 구성요소 docker compose up 실패")
        sys.exit(1)


# ── 프론트엔드 정적 서버 ──────────────────────────────────

def start_frontend() -> None:
    if is_port_in_use(FRONTEND_PORT):
        log(f"포트 {FRONTEND_PORT} 이미 사용 중 → 기존 프로세스 종료 시도")
        run(f"lsof -ti :{FRONTEND_PORT} | xargs kill -9 2>/dev/null")
        time.sleep(0.5)

    os.chdir(PROJECT_DIR)
    write_dev_config_js()

    class QuietHandler(http.server.SimpleHTTPRequestHandler):
        """BrokenPipe / ConnectionReset 등 클라이언트 끊김 에러를 조용히 무시"""
        def log_message(self, format, *args):
            # 기본 로그는 그대로 출력
            super().log_message(format, *args)

        def _should_serve_spa_fallback(self) -> bool:
            path = urllib.parse.urlparse(self.path).path or "/"
            if path == "/r" or path.startswith("/r/"):
                return True
            return False

        def do_GET(self):
            if self._should_serve_spa_fallback():
                original_path = self.path
                self.path = "/index.html"
                try:
                    return super().do_GET()
                finally:
                    self.path = original_path
            return super().do_GET()

        def do_HEAD(self):
            if self._should_serve_spa_fallback():
                original_path = self.path
                self.path = "/index.html"
                try:
                    return super().do_HEAD()
                finally:
                    self.path = original_path
            return super().do_HEAD()

    class QuietServer(http.server.ThreadingHTTPServer):
        def handle_error(self, request, client_address):
            import traceback
            exc = sys.exc_info()[1]
            if isinstance(exc, (BrokenPipeError, ConnectionResetError, ConnectionAbortedError)):
                log(f"⚠ 클라이언트 연결 끊김 ({client_address[0]}:{client_address[1]}) — 무시")
            else:
                super().handle_error(request, client_address)

    httpd = QuietServer(("0.0.0.0", FRONTEND_PORT), QuietHandler)

    thread = threading.Thread(target=httpd.serve_forever, daemon=True)
    thread.start()
    log(f"프론트엔드 서버 시작 → http://localhost:{FRONTEND_PORT}")
    return httpd


def wait_forever(httpd) -> None:
    """Ctrl+C 대기 후 프론트엔드 서버 종료"""
    try:
        signal.pause()
    except (KeyboardInterrupt, AttributeError):
        # Windows에는 signal.pause()가 없으므로 fallback
        try:
            while True:
                time.sleep(1)
        except KeyboardInterrupt:
            pass

    httpd.shutdown()
    log("프론트엔드 서버 종료")


# ── 메인 ──────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="shuttle-go 개발 환경 통합 실행")
    parser.add_argument("--down", action="store_true", help="종료 (기본: backend-blue/backend-green, --all: 전체, --all-no-otp: otp 제외 전체)")
    parser.add_argument("--all", action="store_true", help="모든 구성요소(traefik/postgres/backend-blue/backend-green/prometheus/node-exporter/cadvisor/grafana/otp) 재시작")
    parser.add_argument("--all-no-otp", action="store_true", help="otp 제외 모든 구성요소(traefik/postgres/backend-blue/backend-green/prometheus/node-exporter/cadvisor/grafana) 재시작")
    parser.add_argument("--frontend", action="store_true", help="프론트엔드 서버만 시작")
    parser.add_argument("--traefik", action="store_true", help="traefik만 재시작/종료")
    parser.add_argument("--postgres", action="store_true", help="postgres만 재시작/종료")
    parser.add_argument("--backend", action="store_true", help="backend-blue/backend-green 재시작/종료")
    parser.add_argument("--prometheus", action="store_true", help="prometheus만 재시작/종료")
    parser.add_argument("--node-exporter", dest="node_exporter", action="store_true", help="node-exporter만 재시작/종료")
    parser.add_argument("--grafana", action="store_true", help="grafana만 재시작/종료")
    parser.add_argument("--otp", action="store_true", help="otp만 재시작/종료")
    args = parser.parse_args()
    selected_services = selected_services_from_args(args)
    all_no_otp_services = ordered_services(ALL_EXCEPT_OTP_SERVICES)

    if args.all and args.all_no_otp:
        parser.error("--all과 --all-no-otp는 함께 사용할 수 없습니다.")
    if (args.all or args.all_no_otp) and selected_services:
        parser.error("--all/--all-no-otp와 개별 컴포넌트 플래그(--traefik/--postgres/--backend/--prometheus/--node-exporter/--grafana/--otp)는 함께 사용할 수 없습니다.")
    if args.frontend and (args.down or args.all or args.all_no_otp or selected_services):
        parser.error("--frontend는 단독으로만 사용할 수 있습니다.")

    configure_runtime_ports(validate_conflict=not args.down)

    if args.down:
        if args.all:
            compose_down(all_services=True)
        elif args.all_no_otp:
            compose_down_selected(all_no_otp_services)
        elif selected_services:
            compose_down_selected(selected_services)
        else:
            compose_down(all_services=False)
        log(f"포트 {FRONTEND_PORT} 정리")
        run(f"lsof -ti :{FRONTEND_PORT} | xargs kill -9 2>/dev/null")
        log("완료")
        return

    if args.frontend:
        httpd = start_frontend()
        print()
        log("═══════════════════════════════════════════")
        log(f"  프론트엔드  → {local_url('', FRONTEND_PORT, scheme='http')}")
        log(f"  백엔드 API  → {local_url('/api/sites', BACKEND_HTTP_PORT, scheme='http')}")
        log("═══════════════════════════════════════════")
        log("Ctrl+C 로 종료")
        print()
        wait_forever(httpd)
        return

    if args.all:
        compose_up_all()
    elif args.all_no_otp:
        compose_up_all_except_otp()
    elif selected_services:
        compose_up_selected(selected_services)
    else:
        compose_up_core()
    httpd = start_frontend()

    # 컨테이너 상태 출력
    log("실행 중인 서비스:")
    if args.all:
        run("docker compose ps")
    elif args.all_no_otp:
        run(f"docker compose ps {' '.join(all_no_otp_services)}")
    elif selected_services:
        run(f"docker compose ps {' '.join(selected_services)}")
    else:
        run(f"docker compose ps {' '.join(CORE_SERVICES)}")

    print()
    log("═══════════════════════════════════════════")
    log(f"  프론트엔드  → {local_url('', FRONTEND_PORT, scheme='http')}")
    log(f"  백엔드 API  → {local_url('/api/sites', BACKEND_HTTP_PORT, scheme='http')}")
    if args.all or args.all_no_otp or "prometheus" in selected_services:
        log(f"  Prometheus  → {local_url('/', PROMETHEUS_HOST_PORT, scheme='http')}")
    if args.all or args.all_no_otp or "grafana" in selected_services:
        log(f"  Grafana     → {local_url('/grafana/', BACKEND_HTTP_PORT, scheme='http')}")
    if args.all or "otp" in selected_services:
        log("  OTP 내부주소 → http://otp:8082 (Docker 네트워크)")
    log("═══════════════════════════════════════════")
    log("Ctrl+C 로 프론트엔드 서버 종료 (Docker 컨테이너는 유지)")
    log("전체 종료: python run_dev.py --down")
    print()

    wait_forever(httpd)


if __name__ == "__main__":
    main()
